<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Seeder;

class CurrencyTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Currency::insert([
            array( 'code' => 'AED', 'name' => 'United Arab Emirates dirham', 'status' => 0 ),
            array( 'code' => 'AFN', 'name' => 'Afghan afghani', 'status' => 0 ),
            array( 'code' => 'ALL', 'name' => 'Albanian Lek', 'status' => 0 ),
            array( 'code' => 'AMD', 'name' => 'Armenian Dram', 'status' => 0 ),
            array( 'code' => 'ANG', 'name' => 'Netherlands Antillean gulden', 'status' => 0 ),
            array( 'code' => 'AOA', 'name' => 'Angolan Kwanza', 'status' => 0 ),
            array( 'code' => 'ARS', 'name' => 'Argentine Peso', 'status' => 0 ),
            array( 'code' => 'AUD', 'name' => 'Australian Dollar', 'status' => 0 ),
            array( 'code' => 'AWG', 'name' => 'Aruban Guilder', 'status' => 0 ),
            array( 'code' => 'AZN', 'name' => 'Azerbaijani Manat', 'status' => 0 ),
            array( 'code' => 'BAM', 'name' => 'Bosnia-Herzegovina Conv. Mark', 'status' => 0 ),
            array( 'code' => 'BBD', 'name' => 'Barbados Dollar', 'status' => 0 ),
            array( 'code' => 'BDT', 'name' => 'Bangladeshi taka', 'status' => 0 ),
            array( 'code' => 'BGN', 'name' => 'Bulgarian Lev', 'status' => 0 ),
            array( 'code' => 'BHD', 'name' => 'Bahraini Dinar', 'status' => 0 ),
            array( 'code' => 'BIF', 'name' => 'Burundi Franc', 'status' => 0 ),
            array( 'code' => 'BMD', 'name' => 'Bermuda Dollar', 'status' => 0 ),
            array( 'code' => 'BND', 'name' => 'Brunei Dollar', 'status' => 0 ),
            array( 'code' => 'BOB', 'name' => 'Boliviano', 'status' => 0 ),
            array( 'code' => 'BRL', 'name' => 'Brazilian Real', 'status' => 0 ),
            array( 'code' => 'BSD', 'name' => 'Bahamian Dollar', 'status' => 0 ),
            array( 'code' => 'BTN', 'name' => 'Bhutanese Ngultrum', 'status' => 0 ),
            array( 'code' => 'BWP', 'name' => 'Botswana pula', 'status' => 0 ),
            array( 'code' => 'BYR', 'name' => 'Belarussian Ruble', 'status' => 0 ),
            array( 'code' => 'BZD', 'name' => 'Belize Dollar', 'status' => 0 ),
            array( 'code' => 'CAD', 'name' => 'Canadian Dollar', 'status' => 0 ),
            array( 'code' => 'CDF', 'name' => 'Congolese franc', 'status' => 0 ),
            array( 'code' => 'CHF', 'name' => 'Swiss franc', 'status' => 0 ),
            array( 'code' => 'CLP', 'name' => 'Chilean Peso', 'status' => 0 ),
            array( 'code' => 'CNY', 'name' => 'Chinese Yuan Renminbi', 'status' => 0 ),
            array( 'code' => 'COP', 'name' => 'Colombian Peso', 'status' => 0 ),
            array( 'code' => 'CRC', 'name' => 'Costa Rican colón', 'status' => 0 ),
            array( 'code' => 'CUP', 'name' => 'Cuban peso', 'status' => 0 ),
            array( 'code' => 'CVE', 'name' => 'Cape Verde Escudo', 'status' => 0 ),
            array( 'code' => 'CZK', 'name' => 'Czech koruna', 'status' => 0 ),
            array( 'code' => 'DJF', 'name' => 'Djibouti franc', 'status' => 0 ),
            array( 'code' => 'DKK', 'name' => 'Danish krone', 'status' => 0 ),
            array( 'code' => 'DOP', 'name' => 'Dominican peso', 'status' => 0 ),
            array( 'code' => 'DZD', 'name' => 'Algerian Dinar', 'status' => 0 ),
            array( 'code' => 'EGP', 'name' => 'Egyptian pound', 'status' => 0 ),
            array( 'code' => 'ERN', 'name' => 'Eritrean nakfa', 'status' => 0 ),
            array( 'code' => 'ETB', 'name' => 'Ethiopian birr', 'status' => 0 ),
            array( 'code' => 'EUR', 'name' => 'Euro', 'status' => 1 ),
            array( 'code' => 'FJD', 'name' => 'Fijian dollar', 'status' => 0 ),
            array( 'code' => 'FKP', 'name' => 'Falkland Islands pound', 'status' => 0 ),
            array( 'code' => 'GBP', 'name' => 'Pound sterling', 'status' => 0 ),
            array( 'code' => 'GEL', 'name' => 'Georgian lari', 'status' => 0 ),
            array( 'code' => 'GHC', 'name' => 'Ghanaian cedi', 'status' => 0 ),
            array( 'code' => 'GIP', 'name' => 'Gibraltar pound', 'status' => 0 ),
            array( 'code' => 'GMD', 'name' => 'Gambian dalasi', 'status' => 0 ),
            array( 'code' => 'GNF', 'name' => 'Guinea Franc', 'status' => 0 ),
            array( 'code' => 'GTQ', 'name' => 'Guatemalan quetzal', 'status' => 0 ),
            array( 'code' => 'GYD', 'name' => 'Guyana Dollar', 'status' => 0 ),
            array( 'code' => 'HKD', 'name' => 'Hong Kong dollar', 'status' => 0 ),
            array( 'code' => 'HNL', 'name' => 'Honduran lempira', 'status' => 0 ),
            array( 'code' => 'HRK', 'name' => 'Croatian kuna', 'status' => 0 ),
            array( 'code' => 'HTG', 'name' => 'Haitian gourde', 'status' => 0 ),
            array( 'code' => 'HUF', 'name' => 'Hungarian forint', 'status' => 0 ),
            array( 'code' => 'IDR', 'name' => 'Indonesian rupiah', 'status' => 0 ),
            array( 'code' => 'ILS', 'name' => 'New Israeli Sheqel', 'status' => 0 ),
            array( 'code' => 'INR', 'name' => 'Indian rupee', 'status' => 0 ),
            array( 'code' => 'IQD', 'name' => 'Iraqi dinar', 'status' => 0 ),
            array( 'code' => 'IRR', 'name' => 'Iranian rial', 'status' => 0 ),
            array( 'code' => 'ISK', 'name' => 'Icelandic króna', 'status' => 0 ),
            array( 'code' => 'JMD', 'name' => 'Jamaican dollar', 'status' => 0 ),
            array( 'code' => 'JOD', 'name' => 'Jordanian dinar', 'status' => 0 ),
            array( 'code' => 'JPY', 'name' => 'Japanese yen', 'status' => 0 ),
            array( 'code' => 'KES', 'name' => 'Kenyan shilling', 'status' => 0 ),
            array( 'code' => 'KGS', 'name' => 'Kyrgyzstani som', 'status' => 0 ),
            array( 'code' => 'KHR', 'name' => 'Cambodian riel', 'status' => 0 ),
            array( 'code' => 'KMF', 'name' => 'Comorian Franc', 'status' => 0 ),
            array( 'code' => 'KPW', 'name' => 'North Korean won', 'status' => 0 ),
            array( 'code' => 'KRW', 'name' => 'South Corean won', 'status' => 0 ),
            array( 'code' => 'KWD', 'name' => 'Kuwaiti dinar', 'status' => 0 ),
            array( 'code' => 'KYD', 'name' => 'Cayman Islands Dollar', 'status' => 0 ),
            array( 'code' => 'KZT', 'name' => 'Kazakhstani tenge', 'status' => 0 ),
            array( 'code' => 'LAK', 'name' => 'Lao kip', 'status' => 0 ),
            array( 'code' => 'LBP', 'name' => 'Lebanese pound', 'status' => 0 ),
            array( 'code' => 'LKR', 'name' => 'Sri Lankan rupee', 'status' => 0 ),
            array( 'code' => 'LRD', 'name' => 'Liberian dollar', 'status' => 0 ),
            array( 'code' => 'LSL', 'name' => 'Lesotho loti', 'status' => 0 ),
            array( 'code' => 'LTL', 'name' => 'Lithuanian litas', 'status' => 0 ),
            array( 'code' => 'LVL', 'name' => 'Latvian lats', 'status' => 0 ),
            array( 'code' => 'LYD', 'name' => 'Libyan dinar', 'status' => 0 ),
            array( 'code' => 'MAD', 'name' => 'Moroccan dirham', 'status' => 0 ),
            array( 'code' => 'MDL', 'name' => 'Moldovan leu', 'status' => 0 ),
            array( 'code' => 'MGA', 'name' => 'Malagasy ariary', 'status' => 0 ),
            array( 'code' => 'MKD', 'name' => 'Macedonian denar', 'status' => 0 ),
            array( 'code' => 'MMK', 'name' => 'Myanmar kyat', 'status' => 0 ),
            array( 'code' => 'MNT', 'name' => 'Mongolian tugrug', 'status' => 0 ),
            array( 'code' => 'MOP', 'name' => 'Macanese pataca', 'status' => 0 ),
            array( 'code' => 'MRU', 'name' => 'Mauritanian ouguiya', 'status' => 1 ),
            array( 'code' => 'MUR', 'name' => 'Mauritian rupee', 'status' => 0 ),
            array( 'code' => 'MVR', 'name' => 'Maldivian rufiyaa', 'status' => 0 ),
            array( 'code' => 'MWK', 'name' => 'Malawian kwacha', 'status' => 0 ),
            array( 'code' => 'MXN', 'name' => 'Mexican peso', 'status' => 0 ),
            array( 'code' => 'MYR', 'name' => 'Malaysian ringgit', 'status' => 0 ),
            array( 'code' => 'MZM', 'name' => 'Mozambican metical', 'status' => 0 ),
            array( 'code' => 'NAD', 'name' => 'Namibian dollar', 'status' => 0 ),
            array( 'code' => 'NGN', 'name' => 'Nigerian naira', 'status' => 0 ),
            array( 'code' => 'NIO', 'name' => 'Nicaraguan córdoba', 'status' => 0 ),
            array( 'code' => 'NOK', 'name' => 'Norvegian krone', 'status' => 0 ),
            array( 'code' => 'NPR', 'name' => 'Nepalese rupee', 'status' => 0 ),
            array( 'code' => 'NZD', 'name' => 'New Zealand dollar', 'status' => 0 ),
            array( 'code' => 'OMR', 'name' => 'Omani rial', 'status' => 0 ),
            array( 'code' => 'PAB', 'name' => 'Panamanian balboa', 'status' => 0 ),
            array( 'code' => 'PEN', 'name' => 'Peruvian nuevo sol', 'status' => 0 ),
            array( 'code' => 'PGK', 'name' => 'Papua New Guinean kina', 'status' => 0 ),
            array( 'code' => 'PHP', 'name' => 'Philippine peso', 'status' => 0 ),
            array( 'code' => 'PKR', 'name' => 'Pakistani rupee', 'status' => 0 ),
            array( 'code' => 'PLN', 'name' => 'Polish złoty', 'status' => 0 ),
            array( 'code' => 'PYG', 'name' => 'Paraguayan guaraní', 'status' => 0 ),
            array( 'code' => 'QAR', 'name' => 'Qatari riyal', 'status' => 0 ),
            array( 'code' => 'RON', 'name' => 'Romanian leu', 'status' => 0 ),
            array( 'code' => 'RSD', 'name' => 'Serbian dinar', 'status' => 0 ),
            array( 'code' => 'RUB', 'name' => 'Russian ruble', 'status' => 0 ),
            array( 'code' => 'RWF', 'name' => 'Rwandan franc', 'status' => 0 ),
            array( 'code' => 'SAR', 'name' => 'Saudi riyal', 'status' => 0 ),
            array( 'code' => 'SBD', 'name' => 'Solomon Islands dollar', 'status' => 0 ),
            array( 'code' => 'SCR', 'name' => 'Seychelles rupee', 'status' => 0 ),
            array( 'code' => 'SDG', 'name' => 'Sudanese pound', 'status' => 0 ),
            array( 'code' => 'SEK', 'name' => 'Swedish krona', 'status' => 0 ),
            array( 'code' => 'SGD', 'name' => 'Singapore dollar', 'status' => 0 ),
            array( 'code' => 'SHP', 'name' => 'Saint Helena pound', 'status' => 0 ),
            array( 'code' => 'SLL', 'name' => 'Sierra Leonean leone', 'status' => 0 ),
            array( 'code' => 'SOS', 'name' => 'Somali shilling', 'status' => 0 ),
            array( 'code' => 'SRD', 'name' => 'Suriname dollar', 'status' => 0 ),
            array( 'code' => 'STD', 'name' => 'São Tomé and Príncipe dobra', 'status' => 0 ),
            array( 'code' => 'SYP', 'name' => 'Syrian pound', 'status' => 0 ),
            array( 'code' => 'SZL', 'name' => 'Swazi lilangeni', 'status' => 0 ),
            array( 'code' => 'THB', 'name' => 'Baht', 'status' => 0 ),
            array( 'code' => 'TJS', 'name' => 'Tajikistani somoni', 'status' => 0 ),
            array( 'code' => 'TMT', 'name' => 'Turkmenistani manat', 'status' => 0 ),
            array( 'code' => 'TND', 'name' => 'Tunisian dinar', 'status' => 0 ),
            array( 'code' => 'TOP', 'name' => 'Tongan pa\'anga', 'status' => 0 ),
            array( 'code' => 'TRY', 'name' => 'Turkish new lira', 'status' => 0 ),
            array( 'code' => 'TTD', 'name' => 'Trinidad and Tobago dollar', 'status' => 0 ),
            array( 'code' => 'TWD', 'name' => 'New Taiwan dollar', 'status' => 0 ),
            array( 'code' => 'TZS', 'name' => 'Tanzanian shilling', 'status' => 0 ),
            array( 'code' => 'UAH', 'name' => 'Ukrainian hryvnia', 'status' => 0 ),
            array( 'code' => 'UGX', 'name' => 'Ugandan shilling', 'status' => 0 ),
            array( 'code' => 'USD', 'name' => 'US dollar', 'status' => 1 ),
            array( 'code' => 'UYU', 'name' => 'Uruguayan peso', 'status' => 0 ),
            array( 'code' => 'UZS', 'name' => 'Uzbekistani som', 'status' => 0 ),
            array( 'code' => 'VEF', 'name' => 'Venezuelan bolivar', 'status' => 0 ),
            array( 'code' => 'VND', 'name' => 'Vietnamese dong', 'status' => 0 ),
            array( 'code' => 'VUV', 'name' => 'Vatu', 'status' => 0 ),
            array( 'code' => 'WST', 'name' => 'Samoan tala', 'status' => 0 ),
            array( 'code' => 'XAF', 'name' => 'CFA Franc BEAC', 'status' => 0 ),
            array( 'code' => 'XCD', 'name' => 'East Caribbean dollar', 'status' => 0 ),
            array( 'code' => 'XOF', 'name' => 'CFA Franc BCEAO', 'status' => 0 ),
            array( 'code' => 'XPF', 'name' => 'CFP Franc', 'status' => 0 ),
            array( 'code' => 'YER', 'name' => 'Yemeni rial', 'status' => 0 ),
            array( 'code' => 'ZAR', 'name' => 'South African rand', 'status' => 0 ),
            array( 'code' => 'ZMW', 'name' => 'Zambian kwacha', 'status' => 0 ),
            array( 'code' => 'ZWL', 'name' => 'Zimbabwean dollar', 'status' => 0 ),
        ]);
    }
}
