stages:
   - deploy

deploy_staging:
  stage: deploy
  image:
     name: ubuntu
  before_script:
     - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
     - eval $(ssh-agent -s)
     - echo "$ID_RSA_GITLAB" | tr -d '\r' | ssh-add -
     - mkdir -p ~/.ssh
     - chmod 700 ~/.ssh
     - apt-get install -y rsync
  script:
     - rsync -e "ssh -o StrictHostKeyChecking=no" -atv --delete --progress ./ root@67.223.117.208:/var/www/talabate-web
     - rsync -e "ssh -o StrictHostKeyChecking=no" -atv --delete --progress .env.develop root@67.223.117.208:/var/www/talabate-web.env
     - ssh -o StrictHostKeyChecking=no root@67.223.117.208 "docker-compose -f /var/www/talabate-web/docker-compose.yml up -d --build --force-recreate"
  tags:
     - cicd-runner
  only:
     - develop
