version: '3.8'

services:
  laravel:
    container_name: viora_bo
    build: .
    ports:
      - "7542:80"
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
      - ./storage:/var/www/html/storage
      - /var/www/html/bootstrap
    restart: always
    depends_on:
      - db

  db:
    container_name: viora_bo_db
    image: mysql:8.0
    restart: always
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: viora_bo
      MYSQL_ROOT_PASSWORD: cssCZGty8fr7u7mF
    volumes:
      - db_data_viora_bo:/var/lib/mysql

  phpmyadmin:
    container_name: viora_bo_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: cssCZGty8fr7u7mF

volumes:
  db_data_viora_bo: